REM in windows start download.bat from command prompt this way
REM C:\download.bat 1> log.dat 2>&1
REM it write all output to cmd and save it in file "log.dat"
python.exe cracked.py REM http://www.cracked.com/url-of-article 1....
python.exe cracked.py REM http://www.cracked.com/url-of-article 2....
python.exe cracked.py REM http://www.cracked.com/url-of-article 3....
